name: Update Firefox Extension

on:
  push:
    tags:
      - v*.*.*
      - cifix*
      - unlisted_v*.*.*

jobs:
  build-firefox-extension:
    name: Build Firefox extension artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |-
          cp -r app dist
          # we archive the dist folder and include SHA commit as the last step
          zip -r firefox-extension.zip dist

      - name: Archive firefox-extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: firefox-extension.zip
  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-firefox-extension

    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "18"

      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: firefox-extension

      - name: Install web-ext cli
        run: |-
          npm install --global web-ext
          ls

      - name: Determine channel
        id: determine-channel
        run: |-
          if [[ "${GITHUB_REF##*/}" == unlisted_v* ]]; then
            echo "channel=unlisted" >> "$GITHUB_OUTPUT"
          else
            echo "channel=listed" >> "$GITHUB_OUTPUT"
          fi

      - name: Sign and upload step
        run: |- 
          unzip firefox-extension.zip -d .
          cd dist
          web-ext sign --channel=${{ steps.determine-channel.outputs.channel }} --api-key="${{ secrets.AMO_JWT_ISSUER }}" --api-secret="${{ secrets.AMO_JWT_SECRET }}"
